export const REQUESTING_DATA = "REQUESTING_DATA";
export const RECEIVED_POP_MOVIES = "RECEIVED_POP_MOVIES";
export const RECEIVED_MOVIE = "RECEIVED_MOVIE";
export const RECEIVED_SEARCH_RESULT = "RECEIVED_SEARCH_RESULT";
export const ERASE_MOVIE = "ERASE_MOVIE";
export const ERASE_SEARCH_RESULT = "ERASE_SEARCH_RESULT";
export const RECEIVED_ERROR = "RECEIVED_ERROR";